name: Examples

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start postgres sandbox
        run: docker compose up -d
      - name: Todo
        run: cd examples/todo && cargo run
      - name: Transactions
        run: cd examples/transactions && cargo run
      - name: Stop  postgres sandbox
        run: docker compose down

