name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start postgres sandbox
        run: docker compose up -d
      - name: Test with default feature
        run: cargo test
      - name: Test with all features
        run: cargo test --all-features
      - name: Test without any feature
        run: cargo test --no-default-features
      - name: Stop postgres sandbox
        run: docker compose down

